name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} # Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            MONGO_USERNAME
            MONGO_PASS
            MONGO_DBNAME
            MONGO_LOG_DBNAME
            SNOWFLAKE_USER
            SNOWFLAKE_PASSWORD
            SNOWFLAKE_ACCOUNT
            SNOWFLAKE_WAREHOUSE
            SNOWFLAKE_DATABASE
            SNOWFLAKE_SCHEMA
            SNOWFLAKE_ROLE
            DBT_THREADS
            DBT_TYPE
            GIT_EMAIL
            GIT_NAME
            GIT_USERNAME
            GIT_TOKEN
        env:
          MONGO_USERNAME: ${{secrets.MONGO_USERNAME}}
          MONGO_PASS: ${{secrets.MONGO_PASS}}
          MONGO_DBNAME: ${{secrets.MONGO_DBNAME}}
          MONGO_LOG_DBNAME: ${{secrets.MONGO_LOG_DBNAME}}
          SNOWFLAKE_USER: ${{secrets.SNOWFLAKE_USER}}
          SNOWFLAKE_PASSWORD: ${{secrets.SNOWFLAKE_PASSWORD}}
          SNOWFLAKE_ACCOUNT: ${{secrets.SNOWFLAKE_ACCOUNT}}
          SNOWFLAKE_WAREHOUSE: ${{secrets.SNOWFLAKE_WAREHOUSE}}
          SNOWFLAKE_DATABASE: ${{secrets.SNOWFLAKE_DATABASE}}
          SNOWFLAKE_SCHEMA: ${{secrets.SNOWFLAKE_SCHEMA}}
          SNOWFLAKE_ROLE: ${{secrets.SNOWFLAKE_ROLE}}
          DBT_THREADS: ${{secrets.DBT_THREADS}}
          DBT_TYPE: ${{secrets.DBT_TYPE}}
          GIT_EMAIL: ${{secrets.GIT_EMAIL}}
          GIT_NAME: ${{secrets.GIT_NAME}}
          GIT_USERNAME: ${{secrets.GIT_USERNAME}}
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
